menu:
  - name: home
    route: main
    roles: ['PUBLIC_ACCESS']
  - name: adminer
    route: app.adminer
    roles: ["ROLE_SUPERADMIN"]
    target_blank: true
  - name: detail uživatele
    route: user_detail
    roles: ['ROLE_USER']
    hidden: true
