menu:
  - name: domů
    route: main
    roles: ['PUBLIC_ACCESS']
  - name: zadání
    route: assignments
    roles: ['ROLE_ADMIN']
  - name: uživatelé
    route: users
    routes: ["user"]
    roles: ['ROLE_ADMIN']
  - name: adminer
    route: app.adminer
    roles: ["ROLE_SUPERADMIN"]
    target_blank: true
  - name: detail uživatele
    route: user_detail
    roles: ['ROLE_USER']
    hidden: true
